-- AlterTable
ALTER TABLE "company" ADD COLUMN IF NOT EXISTS "tagline" VARCHAR(300);
ALTER TABLE "company" ADD COLUMN IF NOT EXISTS "phone" VARCHAR(15);
ALTER TABLE "company" ADD COLUMN IF NOT EXISTS "email" VARCHAR(254);
ALTER TABLE "company" ADD COLUMN IF NOT EXISTS "currency" VARCHAR(5) DEFAULT 'INR';
ALTER TABLE "company" ADD COLUMN IF NOT EXISTS "upi_id" VARCHAR(100);
